site_name: Reahill's Notebook
site_url: https://reahill.github.io/
theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
