site_name: Reahill's Notebook
site_url: https://reahill.github.io/
repo_url: https://github.com/Reahill/reahill.github.io
repo_name: reahill.github.io
theme:
  name: material
  language: zh
  font: false
  icon:
    logo: material/robot-dead-outline
    repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.prune
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.indexes
    - navigation.instant
  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://unpkg.com/@fontsource/jetbrains-mono@5.2.6/latin-400.css
  - https://unpkg.com/@fontsource/jetbrains-mono@5.2.6/latin-700.css
  - https://cdn.staticfile.org/lxgw-wenkai-webfont/1.6.0/style.css
  
extra_javascript:
  - js/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js


nav:
  - Home: 
    - index.md
  - Foundation: 
    - foundation/index.md
    - math: 
      - foundation/math/index.md
      - 微积分（甲）Ⅱ: foundation/math/calculus-2/calculus-2.md
      - 常微分方程: foundation/math/ode/ode.md
    - physics: 
      - foundation/physics/index.md
